"""Spawn the ArUco landing pads into the running AAVC SITL world (V1.3).

Run AFTER PX4 SITL + Gazebo have started. Uses the gz CLI (`gz service ...
/world/aavc_field/create`) to inject `landing_pad_id_<k>` models (baked by
tools/gen_pads.py) at seeded-random positions INSIDE the rules' search-area
polygon. `--seed n` picks BOTH a fresh ``n_pads``-of-6 id subset AND fresh
positions (min 25 m separation, 10 m polygon inset) so blind-search
verification doesn't memorise one layout; no seed reproduces the world file's
static baseline.

`n_pads` defaults to 6 (config `sitl.n_pads`, CLI `--n-pads`): the event
briefing puts SIX physical pads on the real field, and the committee assigns
only 4 of them per team, so the mission's `assigned_marker_ids`/queue is
always a 4-subset — the 2 unspawned ids would otherwise be a wrong-id path
that never gets flown against a whole mission. Spawning all 6 by default
makes the other 2 permanent distractors the id-verified LAND gate must keep
rejecting.

The world file (sitl/worlds/aavc_field.sdf) already includes the same baseline
set, so a bare `make px4_sitl` has pads to fly to. This script re-places them
at runtime; it is idempotent — it removes any previously spawned/baseline pad
first, then re-creates.

Ground TRUTH (no GPS error) is written to /tmp/aavc_targets.json as
    {"targets": [{"name", "marker_id", "lat", "lon"}, ...]}
which the post-flight truth audit (orchestrator/audit.py) and the drone-response
verifier (tools/verify_flight.py) compare against — NEVER used for planning
(blind search; the committee only assigns marker ids).

Usage:
    python sitl/spawn_targets.py --config sitl/aavc_config.yaml --seed 42
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
import subprocess
import sys
import time
from pathlib import Path

import yaml

WORLD_NAME = "kmutnb_skyfield"

# WGS84 ellipsoid — gz's world uses <surface_model>EARTH_WGS84</surface_model>,
# so the local ENU↔lat/lon conversion MUST use the ellipsoidal metres-per-degree
# (meridional for north, prime-vertical×cosφ for east). Using the equatorial
# radius for the north axis wrote truth ~0.62% (0.4-0.7 m) south of where gz
# actually renders each pad — a directional bias that inflated every measured
# touchdown-vs-truth distance (G4 2026-07-04).
_WGS84_A = 6_378_137.0
_WGS84_E2 = 6.694379990141316e-3   # first eccentricity squared

# The world file's static baseline (no-seed spawn reproduces it exactly):
# (marker_id, east_m, north_m, yaw_deg) relative to site.center (= the L&R
# point / world origin). Poses mirror sitl/worlds/kmutnb_skyfield.sdf and are
# GENERATED by tools/gen_geo.py (two columns x three rows in the pitch's field
# frame). SIX entries (6 pads on the field, 4 assigned); >=14.5 m from every
# other pad and >=4.5 m inside the search polygon (see
# tests/test_spawn_targets.py for the numeric proof).
BASELINE_PADS = (
    (1, -30.6, 17.3, 0.0),
    (3, -18.9, 25.8, 55.0),
    (4, -7.2, 34.4, 120.0),
    (6, -39.8, 29.8, 240.0),
    (2, -28.1, 38.3, 170.0),
    (5, -16.4, 46.9, 300.0),
)

DEFAULT_N_PADS = 6           # event briefing: 6 pads placed on the field; the
                              # committee assigns 4 per team (sitl.n_pads / --n-pads)
# KMUTNB: the whole search polygon is 30 x 40 m (the KMITL field was ~220 x
# 60), so the placement gates scale with it: 12 m separation still exceeds
# the tracker's serve-dedupe (6 m) and cluster radius (5 m); a 4 m inset
# keeps a 1 m pad fully inside the polygon with GPS slack.
MIN_SEPARATION_M = 12.0      # keep pads well apart (also > tracker dedupe radius)
POLYGON_INSET_M = 4.0        # keep pads off the search-area boundary
# Every pad name that could ever be spawned (ids 1-6, the full DICT_4X4_50
# competition set — NOT just DEFAULT_N_PADS or the configured n_pads), so the
# idempotent pre-spawn cleanup always removes a stale pad from a PRIOR run
# with a higher n_pads even when this run asks for fewer.
_ALL_PAD_NAMES = tuple(f"pad_{i}" for i in range(1, 7))


def _wgs84_m_per_deg(lat0: float) -> tuple[float, float]:
    """(metres per degree of latitude, metres per degree of longitude) on the
    WGS84 ellipsoid at ``lat0`` — matches gz's EARTH_WGS84 local frame."""
    s = math.sin(math.radians(lat0))
    w = math.sqrt(1.0 - _WGS84_E2 * s * s)
    m_lat = math.radians(1.0) * _WGS84_A * (1.0 - _WGS84_E2) / (w ** 3)
    m_lon = math.radians(1.0) * _WGS84_A / w * math.cos(math.radians(lat0))
    return m_lat, m_lon


def _latlon_to_local_enu(
    lat: float, lon: float, lat0: float, lon0: float
) -> tuple[float, float]:
    """Convert (lat, lon) to local ENU offset (m) from origin (lat0, lon0) on
    the WGS84 ellipsoid (= gz's frame). Returns (east_m, north_m)."""
    m_lat, m_lon = _wgs84_m_per_deg(lat0)
    return (lon - lon0) * m_lon, (lat - lat0) * m_lat


def _local_enu_to_latlon(
    east: float, north: float, lat0: float, lon0: float
) -> tuple[float, float]:
    """Inverse of :func:`_latlon_to_local_enu`. Returns (lat, lon)."""
    m_lat, m_lon = _wgs84_m_per_deg(lat0)
    return lat0 + north / m_lat, lon0 + east / m_lon


def _point_in_polygon(x: float, y: float, poly: list[tuple[float, float]]) -> bool:
    """Ray-cast test in local ENU (x=east, y=north)."""
    inside = False
    j = len(poly) - 1
    for i in range(len(poly)):
        xi, yi = poly[i]
        xj, yj = poly[j]
        if (yi > y) != (yj > y):
            x_int = (xj - xi) * (y - yi) / (yj - yi + 1e-12) + xi
            if x < x_int:
                inside = not inside
        j = i
    return inside


def _inset_ok(x: float, y: float, poly: list[tuple[float, float]],
              inset: float) -> bool:
    """Inside the polygon AND at least ``inset`` from every edge (via a probe
    of the four axis-aligned offsets — a cheap, adequate inset test)."""
    return all(_point_in_polygon(x + dx, y + dy, poly)
               for dx, dy in ((inset, 0), (-inset, 0), (0, inset), (0, -inset)))


def _sample_positions(
    poly: list[tuple[float, float]], n: int, rng: random.Random,
) -> list[tuple[float, float]]:
    """Rejection-sample n points inside the polygon, inset + min-separated."""
    xs = [p[0] for p in poly]
    ys = [p[1] for p in poly]
    out: list[tuple[float, float]] = []
    for _ in range(20_000):
        if len(out) >= n:
            break
        x = rng.uniform(min(xs), max(xs))
        y = rng.uniform(min(ys), max(ys))
        if not _inset_ok(x, y, poly, POLYGON_INSET_M):
            continue
        if any(math.hypot(x - ox, y - oy) < MIN_SEPARATION_M for ox, oy in out):
            continue
        out.append((x, y))
    if len(out) < n:
        raise RuntimeError(
            f"could only place {len(out)}/{n} pads inside the search area "
            f"(inset {POLYGON_INSET_M} m, separation {MIN_SEPARATION_M} m)")
    return out


def _gz_remove(name: str) -> None:
    """Remove a model by name (best-effort, for idempotent re-spawn)."""
    request = f'name: "{name}", type: MODEL'
    subprocess.run(
        [
            "gz", "service",
            "-s", f"/world/{WORLD_NAME}/remove",
            "--reqtype", "gz.msgs.Entity",
            "--reptype", "gz.msgs.Boolean",
            "--timeout", "2000",
            "--req", request,
        ],
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def _gz_spawn(
    model_uri: str, name: str, x: float, y: float, z: float, yaw_deg: float = 0.0,
    *, attempts: int = 3,
) -> bool:
    """Spawn a model into the running Gazebo world via gz CLI, at ``yaw_deg``.
    Returns True only when the create service REPLIES success — the gz CLI exits
    0 even on a service timeout, so the exit code alone is not trustworthy; we
    parse the Boolean reply ('data: true') and retry a flaky create."""
    half = math.radians(yaw_deg) / 2.0
    qz, qw = math.sin(half), math.cos(half)
    request = (
        f'sdf_filename: "{model_uri}", name: "{name}", '
        f'pose: {{position: {{x: {x}, y: {y}, z: {z}}}, '
        f'orientation: {{x: 0, y: 0, z: {qz}, w: {qw}}}}}'
    )
    for k in range(attempts):
        proc = subprocess.run(
            [
                "gz", "service",
                "-s", f"/world/{WORLD_NAME}/create",
                "--reqtype", "gz.msgs.EntityFactory",
                "--reptype", "gz.msgs.Boolean",
                "--timeout", "3000",
                "--req", request,
            ],
            capture_output=True, text=True, check=False,
        )
        if proc.returncode == 0 and "data: true" in (proc.stdout or "").lower():
            return True
        if k + 1 < attempts:
            print(f"[spawn] {name}: create not confirmed "
                  f"(attempt {k + 1}/{attempts}) — retrying")
            time.sleep(0.5)
    return False


def _layout(seed: int | None, search_poly_enu: list[tuple[float, float]],
            valid_ids: list[int],
            n_pads: int = DEFAULT_N_PADS) -> list[tuple[int, float, float, float]]:
    """(marker_id, east, north, yaw_deg) per pad. No seed → the world baseline
    (all 6 baseline pads; ``n_pads`` has no effect on this path); a seed picks
    ``n_pads`` distinct ids of the valid set (capped at ``len(valid_ids)``) +
    fresh positions + yaws."""
    if seed is None:
        return list(BASELINE_PADS)
    rng = random.Random(seed)
    k = min(n_pads, len(valid_ids))
    ids = rng.sample(sorted(valid_ids), k=k)
    pts = _sample_positions(search_poly_enu, len(ids), rng)
    yaw_rng = random.Random(seed + 104729)   # independent stream, like the old jitter
    return [(mid, x, y, yaw_rng.uniform(0.0, 360.0))
            for mid, (x, y) in zip(ids, pts, strict=True)]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Spawn the ArUco landing pads into the running SITL world "
                     "(n_pads of them; default 6 — the event briefing's full "
                     "field, of which the committee assigns 4 per team)")
    parser.add_argument(
        "--config", type=Path, default=Path("sitl/aavc_config.yaml"),
        help="Field config providing site.center (ENU origin), search_area, "
             "marker.valid_ids and sitl.n_pads.",
    )
    parser.add_argument(
        "--seed", type=int, default=None,
        help="RNG seed: picks an n_pads-of-6 marker id subset + positions "
             "inside the search area. Omit to reproduce the world file's "
             "static baseline (all 6 baseline pads).",
    )
    parser.add_argument(
        "--n-pads", type=int, default=None,
        help="How many distinct pads to place on a --seed spawn (capped at "
             "len(valid_ids)); has no effect on the no-seed baseline layout. "
             "Omit to use config sitl.n_pads (default 6).",
    )
    parser.add_argument(
        "--emit-targets-json", type=Path, default=Path("/tmp/aavc_targets.json"),
        help="Where to dump ground-TRUTH pad coords + ids (no GPS offset). "
             "Consumed by the post-flight truth audit / verify_flight only "
             "(never planning). Set to /dev/null to disable.",
    )
    args = parser.parse_args()

    cfg = yaml.safe_load(args.config.read_text()) or {}
    lat0 = float(cfg["site"]["center_lat"])
    lon0 = float(cfg["site"]["center_lon"])
    search_poly = [(float(v[0]), float(v[1])) for v in cfg.get("search_area", [])]
    if len(search_poly) < 3:
        raise SystemExit("config has no search_area polygon — cannot place pads")
    poly_enu = [_latlon_to_local_enu(lat, lon, lat0, lon0)
                for lat, lon in search_poly]
    valid_ids = [int(v) for v in cfg.get("marker", {}).get("valid_ids",
                                                           [1, 2, 3, 4, 5, 6])]
    n_pads = (args.n_pads if args.n_pads is not None
              else int(cfg.get("sitl", {}).get("n_pads", DEFAULT_N_PADS)))

    pads = _layout(args.seed, poly_enu, valid_ids, n_pads=n_pads)

    # Idempotent: clear every possible previous pad name first (the world's
    # baseline includes + any earlier runtime spawn).
    for name in _ALL_PAD_NAMES:
        _gz_remove(name)

    truth_targets: list[dict] = []
    failed: list[tuple[str, int]] = []
    for i, (mid, x, y, yaw) in enumerate(pads, start=1):
        name = f"pad_{i}"
        if not _gz_spawn(f"model://landing_pad_id_{mid}", name, x, y, 0.0, yaw):
            failed.append((name, mid))
            print(f"[spawn] FAILED to create {name} (ArUco id {mid}) — the gz "
                  "create service did not confirm")
            continue
        lat, lon = _local_enu_to_latlon(x, y, lat0, lon0)
        # TRUTH holds ONLY pads that actually spawned — never phantom pads.
        truth_targets.append(
            {"name": name, "marker_id": mid, "lat": lat, "lon": lon})
        print(
            f"Spawned {name} (ArUco id {mid}) at local ENU ({x:.2f}, {y:.2f}) "
            f"yaw={yaw:.0f}deg -> TRUTH lat={lat:.7f} lon={lon:.7f}"
        )

    # Dump ground-TRUTH coords (no GPS offset) for the post-flight audit —
    # atomically (tmp + rename) with 0600 perms so a concurrent reader never
    # sees a torn file and another local user can't read/pre-seed it.
    if args.emit_targets_json and str(args.emit_targets_json) != "/dev/null":
        dst = args.emit_targets_json
        dst.parent.mkdir(parents=True, exist_ok=True)
        tmp = dst.with_name(dst.name + ".tmp")
        tmp.write_text(json.dumps({"targets": truth_targets}, indent=2))
        tmp.chmod(0o600)
        os.replace(tmp, dst)
        print(f"[spawn] wrote ground truth -> {dst}")

    if failed:
        print(f"[spawn] ERROR: {len(failed)}/{len(pads)} pads failed to spawn "
              f"({', '.join(n for n, _ in failed)}) — the world is INCOMPLETE",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
