"""Bake the ArUco DICT_4X4_50 bit patterns (ids 1-6) into the GCS bundle.

The pre-flight queue editor shows the operator the *marker picture* the
committee hands them, not a number to translate in their head — so the glyph
must come from the SAME dictionary the flight detector decodes
(vision.detectors.aruco.PAD_DICT). Rendering it from baked bits keeps the GCS
fully offline (no image asset, no endpoint, crisp at any zoom) while
tests/test_aruco_glyphs.py holds the artefact to the dictionary.

Usage:  .venv/bin/python tools/gen_aruco_glyphs.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import cv2

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from vision.detectors.aruco import PAD_DICT, VALID_MARKER_IDS  # noqa: E402

OUT = REPO / "dashboard/web/src/lib/aruco-glyphs.ts"

# A 4x4 marker is 6x6 cells once its mandatory black border is included.
GLYPH_CELLS = 6


def glyph_rows(marker_id: int) -> list[str]:
    """The marker's cells as '1' (white) / '0' (black) rows, border included."""
    img = cv2.aruco.generateImageMarker(
        cv2.aruco.getPredefinedDictionary(PAD_DICT), marker_id, GLYPH_CELLS)
    return ["".join("1" if px else "0" for px in row) for row in img]


def render_module() -> str:
    """The full TS module source (single source of truth for the generator)."""
    entries = "\n".join(
        f"  {mid}: [{', '.join(repr(r).replace(chr(39), chr(34)) for r in glyph_rows(mid))}],"
        for mid in sorted(VALID_MARKER_IDS))
    return f'''// GENERATED by tools/gen_aruco_glyphs.py — do not edit by hand.
// ArUco DICT_4X4_50 bit patterns for the committee-assignable pad ids.
// Each entry is {GLYPH_CELLS}x{GLYPH_CELLS} cells INCLUDING the marker's black
// border; "1" = white cell, "0" = black. Held to the flight detector's
// dictionary by tests/test_aruco_glyphs.py — regenerate, never hand-edit.
export const ARUCO_GLYPH_ROWS: Record<number, string[]> = {{
{entries}
}};

export const ARUCO_GLYPH_CELLS = {GLYPH_CELLS};
'''


def main() -> None:
    OUT.write_text(render_module(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} "
          f"({len(VALID_MARKER_IDS)} glyphs, {GLYPH_CELLS}x{GLYPH_CELLS} cells)")


if __name__ == "__main__":
    main()
