// GENERATED by tools/gen_aruco_glyphs.py — do not edit by hand.
// ArUco DICT_4X4_50 bit patterns for the committee-assignable pad ids.
// Each entry is 6x6 cells INCLUDING the marker's black
// border; "1" = white cell, "0" = black. Held to the flight detector's
// dictionary by tests/test_aruco_glyphs.py — regenerate, never hand-edit.
export const ARUCO_GLYPH_ROWS: Record<number, string[]> = {
  1: ["000000", "000000", "011110", "010010", "010100", "000000"],
  2: ["000000", "000110", "000110", "000100", "011010", "000000"],
  3: ["000000", "010010", "010010", "001000", "001100", "000000"],
  4: ["000000", "001010", "001000", "010010", "011100", "000000"],
  5: ["000000", "001110", "010010", "011000", "011010", "000000"],
  6: ["000000", "010010", "011100", "000100", "011100", "000000"],
};

export const ARUCO_GLYPH_CELLS = 6;
